Create Children and Success Story API Endpoints
ctc-uci/cch pull request #31
Opened 2024-12-20 20:36 UTC by arnavk377

## Description
We created the API Endpoints for Children and Success Story.

## Screenshots/Media
N/A

## Issues
Closes #25

2025-01-10 17:11 UTC, benson-fm requested changes
Good work guys! 

Just adding a minor stuff from there

2025-01-10 17:11 UTC, benson-fm commented on server/routes/children.js
> +childRouter.put("/children/id", async (req, res) => {
remember that its /:id

2025-01-10 17:11 UTC, benson-fm commented on server/routes/children.js
> +
with that being said you would want to get id by doing something like 

const { id } = req.params

2025-01-10 17:11 UTC, benson-fm commented on server/routes/children.js
> +      );
Note there could be a possibility where we only update specific attributes meaning some of these values will be null in the request, we could solve this by using COALESCE as seen [here](https://github.com/ctc-uci/aiss-backend/blob/main/routes/day.js) on line 91

2025-01-10 17:11 UTC, benson-fm commented on server/routes/successStory.js
> +      );
same thing here as mentioned in children.js about the put statement and optional null values

2025-01-12 21:37 UTC, arnavk377 commented on server/routes/successStory.js
> +      const { id } = req.params;
Didn't see a comment for this change, but thought it made sense given the other similar fix at children.js around line 50

2025-01-12 21:40 UTC, srukelman approved these changes
Great Work Guys!

2025-01-12 21:42 UTC, merged